### ISSUE TITLE
Docker Structure For Railway

### ISSUE THREAD

**Issue by gfleetwood** [analythium/railway-shiny#1]
Hi, I noticed that railway.app's [shiny example](https://github.com/railwayapp-templates/shiny/blob/main/Dockerfile) references your Dockerfile. I recently tried deploying a shiny app from scratch, and railway will build and deploy it, but not generate a url. 

is there something I'm missing? Here's my Dockerfile (the last two lines were trying to copy your style);

```
FROM rocker/shiny:4.0.5

RUN apt-get update && apt-get install -y \
    libcurl4-gnutls-dev \
    libssl-dev \
    libxml2-dev \
    unixodbc-dev \
    odbc-postgresql

RUN R -e 'install.packages(c("tidyverse", "rhandsontable", "reactable", "lubridate", "odbc", "DBI", "pool"), \
          repos = "https://packagemanager.rstudio.com/cran/__linux__/focal/2021-04-23")'
          
WORKDIR /home/app
COPY app.R .
ADD ./odbcinst_app.ini /etc/odbcinst.ini

#EXPOSE 3838
#CMD ["R", "-e", "shiny::runApp('/home/app', host = '0.0.0.0', port = 3838)"]

ENV PORT=3838

CMD ["R", "-e", "shiny::runApp('/home/app', host = '0.0.0.0', port= as.numeric(Sys.getenv('PORT')))"]
```

**Comment by psolymos** [comment]
Not sure if it is a typo, but the reason could be `por t=` to `port=` (without the space).

**Comment by gfleetwood** [comment]
It was but a redeploy has the same problem. It's successful but I still don't get a url from Railway.

**Comment by psolymos** [comment]
You should be able to see the link once you click on the card in the Dashboard (`xxxxxx.up.railway.app`).

Can you see the deploy logs? Something like this:

```
> shiny::runApp('/home/app', host = '0.0.0.0', port=as.numeric(Sys.getenv('PORT')))
Loading required package: shiny
Listening on http://0.0.0.0:5691/
```

**Comment by gfleetwood** [comment]
I figured it out. I had to go into the settings and activate the domain. Strange that it's automatic for Python and your docker image, but manual for mine. The domain is taking a long time to work, but that's a question for railway.

Thanks for the help!

**Comment by psolymos** [comment]
Thanks for the update.

For the record, Railway is experiencing some [issues](https://railway.instatus.com/cl8vt7zju50041uwn3e5rwc7qn): _"Delayed Builds. We have pushed a fix and are now monitoring the incident."_
